[workspace]
members = [
  "crates/prismctl-cli",
  "crates/prismctl-core",
  "crates/prismctl-i18n",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.92"
license = "MIT"
repository = "https://github.com/thornboo/prismctl"
