[workspace]
members = [
  "crates/ekko-cli",
  "crates/ekko-core",
  "crates/ekko-i18n",
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/thornboo/ekko"
