[book]
title = "Ekko Documentation"
authors = ["thornboo"]
language = "zh-CN"
src = "."

[build]
build-dir = "../../book-output/zh-CN"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/thornboo/Ekko"
edit-url-template = "https://github.com/thornboo/Ekko/edit/master/docs/zh-CN/{path}"
site-url = "/Ekko/zh-CN/"

[output.html.search]
enable = true
limit-results = 30
